# Discord key
discord:
  refresh-commands: 'false'
  bots:
    c-3po:
      discord-id: 1172743069523791902
      discord-secret: ${C3PO_DISCORD_SECRET}
    invocador:
      discord-id: 1191517545900023880
      discord-secret: ${INVOCADOR_DISCORD_SECRET}
    invisible-friend:
        discord-id: 1192225344665686036
        discord-secret: ${INVISIBLE_FRIEND_DISCORD_SECRET}

# MongoDB
spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}.mongodb.net/
      database: ${MONGODB_DATABASE}