# Discord key
discord:
  refresh-commands: 'true'
  bots:
    c-3po:
      discord-id: 1172743069523791902
      discord-secret: ${C3PO_DISCORD_SECRET}
    invocador:
      discord-id: 1191517545900023880
      discord-secret: ${INVOCADOR_DISCORD_SECRET}